# Generated by Django 4.1 on 2022-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiles_location_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='social_stackoverflow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
